### ISSUE TITLE
Multiple occurrences of same option letter

### ISSUE THREAD

**Issue by gfiedler** [willamowius/ptlib#6] opened 2018-08-14 10:23 UTC
When I follow the README in `plugins/sound_pulse` to let the audio tool report the available 
sound devices, then I get the following error:

```
# obj_linux_x86_64/audio -r
      assert.cxx(114)   PWLib   Assertion fail: Multiple occurrences of same option letter, file ptlib/common/osutils.cxx, line 1189, Error=20
Assertion fail: Multiple occurrences of same option letter, file ptlib/common/osutils.cxx, line 1189, Error=20

Dumping core.
Aborted (core dumped)
```

**Comment by willamowius** [comment] 2018-08-16 09:37
That issue was actually caused by a memory violation in the argument parsing. Thanks for reporting. Its fixed now.

**Closed as completed by willamowius** 2018-08-16 09:37 UTC
